# _config.yml
title: Can We Challenge Open-Vocabulary Object Detectors with Generated Content in Street Scenes?
email: your-email@example.com
description: >-
  Project site for Can We Challenge Open-Vocabulary Object Detectors with Generated Content in Street Scenes?.

url: "https://marcoschumacher-uniwuppertal.github.io"
baseurl: "/"


#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: "Admin"
  avatar: ""
  bio: ""
  location: "Wuppertal, Germany"


#latex support
markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

mathjax: true